In [17]:
import pandas as pd
dataset=pd.read_csv("CKD.csv")
dataset=pd.get_dummies(dataset, drop_first = True, dtype =int)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [18]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [19]:
ind=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep = dataset[['classification_yes']]

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(ind, dep, test_size=0.3, random_state=0)

In [21]:
#Decision Tree doesn't need StandardScaler. Because it works based on features not distance.(see your notes)
#from sklearn.preprocessing import StandardScaler
#scx = StandardScaler()
#X_train = scx.fit_transform(X_train)
#X_test = scx.transform(X_test)
#scy = StandardScaler()
#y_train = scy.fit_transform(y_train)
#y_test = scy.transform(y_test)
#from sklearn.preprocessing import LabelEncoder
#lex = LabelEncoder()
#X_train = lex.fit_transform(X_train)
#X_test = lex.transform(X_test)
#ley = LabelEncoder()
#y_train = ley.fit_transform(y_train)
#y_test = ley.transform(y_test)

In [22]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
from sklearn.tree import DecisionTreeClassifier

param_grid = {'criterion':['gini','entropy'],
              'max_features': [1, 'sqrt','log2'],
              'splitter':['best','random']}

grid = GridSearchCV(DecisionTreeClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1, cv=KFold(), scoring='f1_weighted')

grid.fit(X_train, y_train)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': [1, 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [23]:
re=grid.cv_results_
table=pd.DataFrame.from_dict(re)
table.to_excel("DT_Class_GRID.xlsx", index=False)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005663,0.002307,0.015554,0.003519,gini,1,best,"{'criterion': 'gini', 'max_features': 1, 'spli...",0.964808,0.910389,0.964572,0.910571,1.000000,0.950068,0.034800,7
1,0.009812,0.002105,0.015343,0.002630,gini,1,random,"{'criterion': 'gini', 'max_features': 1, 'spli...",0.964286,0.910389,0.964572,0.910800,1.000000,0.950009,0.034705,8
2,0.008863,0.002595,0.015343,0.002877,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.982282,0.928571,0.894269,0.946342,0.981939,0.946681,0.033424,10
3,0.007329,0.002574,0.008991,0.000959,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.982282,0.982078,0.964286,0.964286,0.928177,0.964222,0.019719,3
4,0.004720,0.001507,0.006995,0.001012,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.930400,0.946586,0.946663,0.982114,0.945039,0.950161,0.017104,6
5,0.003241,0.001432,0.008052,0.001685,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.930400,0.964472,0.982051,0.982160,0.981939,0.968204,0.020091,2
6,0.004215,0.001289,0.007563,0.000866,entropy,1,best,"{'criterion': 'entropy', 'max_features': 1, 's...",0.946846,0.982078,0.911692,0.964286,0.928831,0.946746,0.024923,9
7,0.004275,0.001141,0.008002,0.000862,entropy,1,random,"{'criterion': 'entropy', 'max_features': 1, 's...",0.947529,0.928943,0.928571,0.928571,0.981939,0.943111,0.020740,11
8,0.003179,0.001887,0.011141,0.003708,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.927232,0.964286,0.964572,0.946342,0.981680,0.956822,0.018542,4
9,0.003924,0.002043,0.010265,0.003430,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.982282,0.964472,0.964572,0.982114,1.000000,0.978688,0.013268,1
10,0.004829,0.002805,0.009893,0.002522,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.964808,0.945724,0.876368,0.928295,0.963636,0.935766,0.032568,12
11,0.004690,0.000416,0.005064,0.001367,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.912548,0.946586,0.964286,0.946480,0.981939,0.950368,0.023023,5

In [24]:
grid_pred = grid.predict(X_test)

In [25]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_pred)
#print(cm)

In [26]:
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_pred)
#print(clf_report)

In [27]:
from sklearn.metrics import roc_auc_score
ras = roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])
#Receiver-operating characteristic curve (ROC) Area under the curve (AUC)
#This roc_auc_score needs probability as one of the inputs. Sowe used predict_proba fuction (from GridSearchCV)
#[:,1] this is just which rows and colums have this probaility values. Here..[:,1] mean..each rows and first collumn.

In [28]:
print("Evaluation metrics details for DT are given below")
print("1) Confusion Matrix:\n",cm)
print('2) classification report:\n', clf_report)
print("3) roc_auc_score is", ras)
print("4) The best parameters from GridSearchCV for the created DT model are : \n" , grid.best_params_)

Evaluation metrics details for DT are given below
1) Confusion Matrix:
 [[45  0]
 [ 7 68]]
2) classification report:
               precision    recall  f1-score   support

           0       0.87      1.00      0.93        45
           1       1.00      0.91      0.95        75

    accuracy                           0.94       120
   macro avg       0.93      0.95      0.94       120
weighted avg       0.95      0.94      0.94       120

3) roc_auc_score is 0.9533333333333334
4) The best parameters from GridSearchCV for the created DT model are :
 {'criterion': 'entropy', 'max_features': 'sqrt', 'splitter': 'random'}

In [29]:
result = grid.predict([[2, 76.4599483204134, 3, 0, 148.112676056338, 57.4821052631579, 3.0773560209424, 137.52875399361, 4.62724358974359, 12.5181556195965, 38.8689024390243, 8408.19112627986, 4.70559701492537, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,1,1,0]])
result

C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [30]:
if result[0] == 1:
    print("The patient is dignosed with CKD")
else:
    print("CKD is negative")

The patient is dignosed with CKD

In [31]:
#Optional step. if you want to see any other attributes from GridSearchCV
print("The best paramenters in model are", grid.best_params_)

The best paramenters in model are {'criterion': 'entropy', 'max_features': 'sqrt', 'splitter': 'random'}

In [32]:
#Optional step. if you want to see the any one of the values from classification report
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
f1_weighted=f1_score(y_test,grid_pred,average='weighted')
f1_macro=f1_score(y_test,grid_pred,average='macro')
Accuracy=accuracy_score(y_test,grid_pred)
#print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_weighted)
print("The f1_weighted, f1_macro and accuracy values for the best parameters:", grid.best_params_, "are", f1_weighted ,",", f1_macro, "&", Accuracy, "respectively")
#https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html#sklearn.metrics.f1_score

The f1_weighted, f1_macro and accuracy values for the best parameters: {'criterion': 'entropy', 'max_features': 'sqrt', 'splitter': 'random'} are 0.9423437387354914 , 0.9394420012976714 & 0.9416666666666667 respectively