In [1]:
import pandas as pd
dataset = pd.read_csv("CKD.csv")
dataset = pd.get_dummies(dataset, drop_first=True, dtype=int)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [2]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [3]:
ind=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep = dataset[['classification_yes']]

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(ind, dep, test_size = 0.3 , random_state=0)

In [5]:
# from sklearn.preprocessing import StandardScaler
# scx = StandardScaler()
# X_train = scx.fit_transform(X_train)
# X_test = scx.transform(X_test)
# scy = StandardScaler()
# y_train = scy.fit_transform(y_train)
# y_test = scy.transform(y_test)

In [6]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
from sklearn.linear_model import LogisticRegression
param_grid = {'solver' : ['lbfgs', 'liblinear', 'newton-cg' , 'newton-cholesky', 'sag', 'saga'],
              'C' : [0.01, 0.1, 1.0]}
grid = GridSearchCV(LogisticRegression(), param_grid, refit=True, verbose=3,n_jobs=-1,cv=KFold(), scoring = 'f1_weighted')
grid.fit(X_train, y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

C:\Anaconda3\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GridSearchCV(cv=KFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1.0],
                         'solver': ['lbfgs', 'liblinear', 'newton-cg',
                                    'newton-cholesky', 'sag', 'saga']},
             scoring='f1_weighted', verbose=3)

In [7]:
grid_pred = grid.predict(X_test)

In [8]:
re = grid.cv_results_
table = pd.DataFrame.from_dict(re)
table.to_excel("Log_Reg_Clas_Grid.xlsx")
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.056034,0.005332,0.011120,0.001755,0.01,lbfgs,"{'C': 0.01, 'solver': 'lbfgs'}",0.892857,0.946793,0.893717,0.892857,0.963636,0.917972,0.030873,11
1,0.011133,0.002403,0.011803,0.002261,0.01,liblinear,"{'C': 0.01, 'solver': 'liblinear'}",0.928571,0.946586,0.911105,0.910800,0.981680,0.935749,0.026489,9
2,0.090873,0.012739,0.010479,0.002031,0.01,newton-cg,"{'C': 0.01, 'solver': 'newton-cg'}",0.946846,0.946586,0.929513,0.910107,0.981680,0.942946,0.023612,7
3,0.030131,0.001679,0.008556,0.001034,0.01,newton-cholesky,"{'C': 0.01, 'solver': 'newton-cholesky'}",0.946846,0.946586,0.929513,0.910107,0.981680,0.942946,0.023612,7
4,0.016921,0.004527,0.008082,0.002251,0.01,sag,"{'C': 0.01, 'solver': 'sag'}",0.571805,0.436998,0.480769,0.373754,0.541107,0.480887,0.071128,13
5,0.018319,0.002179,0.008909,0.001182,0.01,saga,"{'C': 0.01, 'solver': 'saga'}",0.571805,0.436998,0.480769,0.373754,0.541107,0.480887,0.071128,13
6,0.027857,0.009418,0.008108,0.002834,0.10,lbfgs,"{'C': 0.1, 'solver': 'lbfgs'}",0.909927,0.910977,0.911105,0.910800,0.981680,0.924898,0.028394,10
7,0.007102,0.001011,0.010156,0.001674,0.10,liblinear,"{'C': 0.1, 'solver': 'liblinear'}",0.946846,0.982195,0.964572,0.892857,1.000000,0.957294,0.036764,6
8,0.083957,0.005878,0.009674,0.001342,0.10,newton-cg,"{'C': 0.1, 'solver': 'newton-cg'}",0.964808,0.982195,0.947015,0.928295,0.981680,0.960799,0.020767,4
9,0.013358,0.002029,0.010319,0.001469,0.10,newton-cholesky,"{'C': 0.1, 'solver': 'newton-cholesky'}",0.964808,0.982195,0.947015,0.928295,0.981680,0.960799,0.020767,4
10,0.015902,0.002811,0.008383,0.001384,0.10,sag,"{'C': 0.1, 'solver': 'sag'}",0.571805,0.436998,0.480769,0.373754,0.541107,0.480887,0.071128,13
11,0.017525,0.002267,0.009301,0.001145,0.10,saga,"{'C': 0.1, 'solver': 'saga'}",0.571805,0.436998,0.480769,0.373754,0.541107,0.480887,0.071128,13
12,0.023286,0.004098,0.008001,0.000921,1.00,lbfgs,"{'C': 1.0, 'solver': 'lbfgs'}",0.909927,0.946586,0.893717,0.856590,0.927273,0.906818,0.030673,12
13,0.009512,0.001645,0.009140,0.000909,1.00,liblinear,"{'C': 1.0, 'solver': 'liblinear'}",1.000000,0.964286,0.964572,0.964286,1.000000,0.978629,0.017450,1
14,0.073254,0.007925,0.003202,0.003922,1.00,newton-cg,"{'C': 1.0, 'solver': 'newton-cg'}",1.000000,0.964286,0.964572,0.946064,1.000000,0.974984,0.021498,2
15,0.009357,0.002072,0.009031,0.001197,1.00,newton-cholesky,"{'C': 1.0, 'solver': 'newton-cholesky'}",1.000000,0.964286,0.964572,0.946064,1.000000,0.974984,0.021498,2
16,0.014936,0.001730,0.006995,0.000948,1.00,sag,"{'C': 1.0, 'solver': 'sag'}",0.571805,0.436998,0.480769,0.373754,0.541107,0.480887,0.071128,13
17,0.015078,0.002730,0.005299,0.004058,1.00,saga,"{'C': 1.0, 'solver': 'saga'}",0.571805,0.436998,0.480769,0.373754,0.541107,0.480887,0.071128,13

In [9]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_pred)
#print(cm)

In [10]:
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_pred)
#print(clf_report)

In [11]:
from sklearn.metrics import roc_auc_score
ras = roc_auc_score(y_test, grid.predict_proba(X_test)[:,1])

In [12]:
print("Evaluation metrics details for Logistic Regression Classification are given below")
print("1) Confusion Matrix:\n",cm)
print('2) classification report:\n', clf_report)
print("3) roc_auc_score is", ras)
print("4) The best parameters from GridSearchCV for the created Logistic Regression Classification model are : \n" , grid.best_params_)

Evaluation metrics details for Logistic Regression Classification are given below
1) Confusion Matrix:
 [[43  2]
 [ 0 75]]
2) classification report:
               precision    recall  f1-score   support

           0       1.00      0.96      0.98        45
           1       0.97      1.00      0.99        75

    accuracy                           0.98       120
   macro avg       0.99      0.98      0.98       120
weighted avg       0.98      0.98      0.98       120

3) roc_auc_score is 0.9976296296296296
4) The best parameters from GridSearchCV for the created Logistic Regression Classification model are :
 {'C': 1.0, 'solver': 'liblinear'}

In [13]:
result = grid.predict([[2, 76.4599483204134, 3, 0, 148.112676056338, 57.4821052631579, 3.0773560209424, 137.52875399361, 4.62724358974359, 12.5181556195965, 38.8689024390243, 8408.19112627986, 4.70559701492537, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,1,1,0]])
result

C:\Anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1])

In [14]:
#optional step for practice
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
f1_weighted = f1_score(y_test, grid_pred, average="weighted")
f1_macro = f1_score(y_test, grid_pred, average="macro")
accuracy = accuracy_score(y_test, grid_pred)
best_param = grid.best_params_
print("The f1_weighted, f1_macro and accuracy values for the best parameters:", best_param,  "are", f1_weighted ,",", f1_macro, "&", accuracy, "respectively")

The f1_weighted, f1_macro and accuracy values for the best parameters: {'C': 1.0, 'solver': 'liblinear'} are 0.9832535885167464 , 0.9820574162679425 & 0.9833333333333333 respectively